// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJq-cHeQTenWl2uvbzcrUcrCNsEB7CKUA',
    appId: '1:743130611552:web:784e94599318b47074a805',
    messagingSenderId: '743130611552',
    projectId: 'fcm-practice-c775a',
    authDomain: 'fcm-practice-c775a.firebaseapp.com',
    storageBucket: 'fcm-practice-c775a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzTbjnqR8l1YfbkULIK691Hcj56OhbYfw',
    appId: '1:743130611552:android:da61fa98a4c4629674a805',
    messagingSenderId: '743130611552',
    projectId: 'fcm-practice-c775a',
    storageBucket: 'fcm-practice-c775a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGP6DZDCSEn-bThKPIucnF9Et3r7nerNo',
    appId: '1:743130611552:ios:65e9ae46296258b474a805',
    messagingSenderId: '743130611552',
    projectId: 'fcm-practice-c775a',
    storageBucket: 'fcm-practice-c775a.firebasestorage.app',
    iosBundleId: 'com.example.fcmPractices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGP6DZDCSEn-bThKPIucnF9Et3r7nerNo',
    appId: '1:743130611552:ios:65e9ae46296258b474a805',
    messagingSenderId: '743130611552',
    projectId: 'fcm-practice-c775a',
    storageBucket: 'fcm-practice-c775a.firebasestorage.app',
    iosBundleId: 'com.example.fcmPractices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJq-cHeQTenWl2uvbzcrUcrCNsEB7CKUA',
    appId: '1:743130611552:web:082ec04c347cf84374a805',
    messagingSenderId: '743130611552',
    projectId: 'fcm-practice-c775a',
    authDomain: 'fcm-practice-c775a.firebaseapp.com',
    storageBucket: 'fcm-practice-c775a.firebasestorage.app',
  );
}
