// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGUQC2PQYYFQziTmHJBDY5QBuxOajT3yU',
    appId: '1:160982994310:web:d704e302b005a34d23b007',
    messagingSenderId: '160982994310',
    projectId: 'auth-practice-3a873',
    authDomain: 'auth-practice-3a873.firebaseapp.com',
    storageBucket: 'auth-practice-3a873.firebasestorage.app',
    measurementId: 'G-HB916Q2XSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMm1-3g1gG9wMjcGi5JNB5oCk1EqXvIaw',
    appId: '1:160982994310:android:f672b4183371b35e23b007',
    messagingSenderId: '160982994310',
    projectId: 'auth-practice-3a873',
    storageBucket: 'auth-practice-3a873.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqT70AAp_qKlX3jZud0MB-9GK7p4MzZSc',
    appId: '1:160982994310:ios:5a990935167e076623b007',
    messagingSenderId: '160982994310',
    projectId: 'auth-practice-3a873',
    storageBucket: 'auth-practice-3a873.firebasestorage.app',
    iosBundleId: 'com.example.authPractices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqT70AAp_qKlX3jZud0MB-9GK7p4MzZSc',
    appId: '1:160982994310:ios:5a990935167e076623b007',
    messagingSenderId: '160982994310',
    projectId: 'auth-practice-3a873',
    storageBucket: 'auth-practice-3a873.firebasestorage.app',
    iosBundleId: 'com.example.authPractices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGUQC2PQYYFQziTmHJBDY5QBuxOajT3yU',
    appId: '1:160982994310:web:ee6041927d668e3d23b007',
    messagingSenderId: '160982994310',
    projectId: 'auth-practice-3a873',
    authDomain: 'auth-practice-3a873.firebaseapp.com',
    storageBucket: 'auth-practice-3a873.firebasestorage.app',
    measurementId: 'G-BMK800CJZ4',
  );
}
